FROM nginx:stable-alpine

COPY ./nginx_config.conf /etc/nginx/conf.d/default.conf

RUN mkdir /static /logs

# COPY ./odsc/security_dependency_check/web/static /static

RUN chown -R nginx:nginx /static && chmod 755 -R /static